### PR TITLE
Removed all imports referring directly to logback.

### PR DESCRIPTION
**Pull request by FlorianLautenschlager**
In my case the code produces an ClassCastException due to a cast to logback but i am using log4j2.
- Removed all static code blocks that cast to logback to set the log level (should be configured in the logger configuration).
- Now the code uses the abstraction layer slf4j.

### CODE REVIEW

**Comment by seninp** [comment]
Will see how it works for upstream libs, Thanks!

**Comment by seninp** [comment]
@FlorianLautenschlager: Wonder how to set the log level programmatically after this change? Thanks!

**Comment by FlorianLautenschlager** [comment]
One has to implement helper that knows the logging framework (the only one who knows).
```
import org.slf4j.LoggerFactory;
import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;

Logger root = (Logger)LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
root.setLevel(Level.INFO);
```

But who needs to set the log level programmatically? 
This is usually done by a configuration file.

**Comment by seninp** [comment]
Alright, all makes sense. I usually tinker with the code in eclipse following whatever thoughts I had, so switching logging on/off in place makes sense... Used a simple slf4j logger for the current code version, will push the build to Central later today. Thanks!

**Pull request merged**
